[package]
name = "bak"
version = "0.1.0"
edition = "2021"
description = "A simple backup tool"
authors = ["InCogNiTo124"]
license = "MIT"

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
